# Generated by Django 6.1.1 on 2026-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNR_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
