from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from CNR_app.views import (
    CustomTokenObtainPairView,
    CurrentUserProfileView,
    RecordCreditSaleView,
    UserListCreateView,
    UserDetailView,
    StationListCreateView,
    FuelProductListCreateView,
    FuelPriceUpdateView,
    TankListCreateView,
    PumpListCreateView,
    NozzleListCreateView,
    StartShiftView, 
    RecordClosingMetersView, 
    ReconcileShiftView, 
    ShiftListView,
    RecordDipReadingView, 
    RecordDeliveryView, 
    TankStockVarianceView,
    CreditCustomerListCreateView,
    CreditCustomerDetailView,
    RecordCreditPaymentView,
    ExecutiveDashboardAnalyticsView,
    StockSummaryAnalyticsView,
    AuditLogListView
)
urlpatterns = [
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/me/', CurrentUserProfileView.as_view(), name='user_profile'),
    path('users/', UserListCreateView.as_view(), name='user_list_create'),
    path('users/<uuid:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('stations/', StationListCreateView.as_view(), name='station_list_create'),
    path('fuel-products/', FuelProductListCreateView.as_view(), name='fuel_product_list_create'),
    path('fuel-products/<uuid:pk>/update-price/', FuelPriceUpdateView.as_view(), name='fuel_price_update'),
    path('tanks/', TankListCreateView.as_view(), name='tank_list_create'),
    path('pumps/', PumpListCreateView.as_view(), name='pump_list_create'),
    path('nozzles/', NozzleListCreateView.as_view(), name='nozzle_list_create'),
    path('shifts/', ShiftListView.as_view(), name='shift_list'),
    path('shifts/start/', StartShiftView.as_view(), name='shift_start'),
    path('shifts/<uuid:pk>/close-meters/', RecordClosingMetersView.as_view(), name='shift_close_meters'),
    path('shifts/<uuid:pk>/reconcile/', ReconcileShiftView.as_view(), name='shift_reconcile'),
    path('tanks/<uuid:pk>/dip/', RecordDipReadingView.as_view(), name='tank_dip'),
    path('tanks/<uuid:pk>/variance/', TankStockVarianceView.as_view(), name='tank_variance'),
    path('deliveries/', RecordDeliveryView.as_view(), name='record_delivery'),
    path('credit-customers/', CreditCustomerListCreateView.as_view(), name='credit_customer_list_create'),
    path('credit-customers/<uuid:pk>/', CreditCustomerDetailView.as_view(), name='credit_customer_detail'),
    path('credit-customers/<uuid:pk>/payments/', RecordCreditPaymentView.as_view(), name='record_credit_payment'),
    path('credit-customers/<uuid:pk>/sales/', RecordCreditSaleView.as_view(), name='credit-customer-sale'),
    path('analytics/dashboard/', ExecutiveDashboardAnalyticsView.as_view(), name='analytics_dashboard'),
    path('analytics/stock-summary/', StockSummaryAnalyticsView.as_view(), name='analytics_stock_summary'),
    path('audit-logs/', AuditLogListView.as_view(), name='audit_logs'),
]